---
title: "TestAppCapRecap"
author: "Chris"
date: '2022-06-20'
output: html_document
---

```{r}
install.packages("gganimate")
install.packages("gapminder")
install.packages("ggthemes")
install.packages("ggrepel")

library("tidyverse")
library("ggplot2")
library("gganimate")
library("dplyr")
library("gapminder")
library("ggthemes")
library("ggrepel")
```

```{r}
calls <- read_csv("nyc_rodent_compliants.csv")
```

```{r}
df_NYC <-
  calls %>%
  mutate(Date = as.Date(`Created Date`, format = "%m/%d/%Y"),
        Month_Year = format(Date, "%m/%Y")) %>%
  filter(Descriptor == "Rat Sighting") %>%
  select( BBL, Borough, `Incident Zip`, Month_Year) %>%
  na.omit() %>%
  group_by(BBL, Borough, `Incident Zip`, Month_Year) %>%
  summarize(count = n()) %>%
  filter(BBL != 0, Borough > 10000)

df_NYC <- rename(df_NYC, Zip  = `Incident Zip` )
df_NYC <- df_NYC %>% filter(Zip %in% (10001:11697))
df_NYC <- separate(df_NYC, "Month_Year", c("Month","Year"), sep = "/")
df_NYC <- df_NYC[order(df_NYC$Year),]
```

```{r calls Bronx}

df_Central_Bronx <- df_NYC %>% filter(Zip%in% c(10453, 10457, 10460))
  df_Central_Bronx$Neighborhood <- "CENTRAL BRONX"

df_Bronx_Park_Fordham <- df_NYC %>% filter(Zip%in% c(10458, 10467, 10468))
  df_Bronx_Park_Fordham$Neighborhood <- "BRONX PARK AND FORDHAM"

df_High_Bridge_Morrisania <- df_NYC %>% filter(Zip%in% c(10451, 10452, 10456))
  df_High_Bridge_Morrisania$Neighborhood <- "HIGH BRIDGE AND MORRISANIA"

df_Hunts_Point_Mott_Haven <- df_NYC %>% filter(Zip%in% c(10454, 10455, 10459, 10474))
  df_Hunts_Point_Mott_Haven$Neighborhood <- "HUNTS POINT AND MOTT HAVEN"

df_Kingsbridge_Riverdale <- df_NYC %>% filter(Zip%in% c(10463, 10471))
  df_Kingsbridge_Riverdale$Neighborhood <- "KINGSBRIDGE AND RIVERDALE"

df_Northeast_Bronx <- df_NYC %>% filter(Zip%in% c(10466, 10469, 10470, 10475))
  df_Northeast_Bronx$Neighborhood <- "NORTHEAST BRONX"

df_Southeast_Bronx <- df_NYC %>% filter(Zip%in% c(10461, 10462, 10464, 10465, 10472, 10473))
  df_Southeast_Bronx$Neighborhood <- "SOUTHEAST BRONX"

df_The_Bronx <- rbind(df_Central_Bronx, df_Bronx_Park_Fordham, df_High_Bridge_Morrisania, df_Hunts_Point_Mott_Haven, df_Kingsbridge_Riverdale, df_Northeast_Bronx, df_Southeast_Bronx)

```

```{r calls Brooklyn}

df_Central_Brooklyn <- df_NYC %>% filter(Zip%in% c(11212, 11213, 11216, 11233, 11238))
  df_Central_Brooklyn$Neighborhood <- "CENTRAL BROOKLYN"

df_Southwest_Brooklyn <- df_NYC %>% filter(Zip%in% c(11209, 11214, 11228))
  df_Southwest_Brooklyn$Neighborhood <- "SOUTHWEST BROOKLYN"

df_Borough_Park <- df_NYC %>% filter(Zip%in% c(11204, 11218, 11219, 11230))
  df_Borough_Park$Neighborhood <- "BOROUGH PARK"
  
df_Canarsie_Flatlands <- df_NYC %>% filter(Zip%in% c(11234, 11236, 11239))
  df_Canarsie_Flatlands$Neighborhood <- "CANARSIE AND FLATLANDS"
  
df_Southern_Brooklyn <- df_NYC %>% filter(Zip%in% c(11223, 11224, 11229, 11235))
  df_Southern_Brooklyn$Neighborhood <- "SOUTHERN BROOKLYN"
  
df_Northwest_Brooklyn <- df_NYC %>% filter(Zip%in% c(11201, 11205, 11215, 11217, 11231))
  df_Northwest_Brooklyn$Neighborhood <- "NORTHWEST BROOKLYN"

df_Flatbush <- df_NYC %>% filter(Zip%in% c(11203, 11210, 11225, 11226))
  df_Flatbush$Neighborhood <- "FLATBUSH"

df_East_NY_New_Lots <- df_NYC %>% filter(Zip%in% c(11207, 11208))
  df_East_NY_New_Lots$Neighborhood <- "EAST NEW YORK AND NEW LOTS"
  
df_Greenpoint <- df_NYC %>% filter(Zip%in% c(11211, 11222))
  df_Greenpoint$Neighborhood <- "GREENPOINT"
  
df_Bushwick_Williamsburg <- df_NYC %>% filter(Zip%in% c(11220, 11232))
  df_Bushwick_Williamsburg$Neighborhood <- "BUSHWICK AND WILLIAMSBURG"
  
df_Sunset_Park <- df_NYC %>% filter(Zip%in% c(11206, 11221, 12237))
  df_Sunset_Park$Neighborhood <- "SUNSET PARK"

df_Brooklyn <- rbind(df_Central_Brooklyn, df_Southwest_Brooklyn, df_Borough_Park, df_Canarsie_Flatlands, df_Southern_Brooklyn, df_Northwest_Brooklyn, df_Flatbush, df_East_NY_New_Lots, df_Greenpoint, df_Bushwick_Williamsburg, df_Sunset_Park)

```

```{r calls Manhattan}

df_Central_Harlem <- df_NYC %>% filter(Zip%in% c(10026, 10027, 10030, 10037, 10039))
  df_Central_Harlem$Neighborhood <- "CENTRAL HARLEM"

df_Chelsea_Clinton <- df_NYC %>% filter(Zip%in% c(10001, 10011, 10018, 10019, 10020, 10036))
  df_Chelsea_Clinton$Neighborhood <- "CHELSEA AND CLINTON"

df_East_Harlem <- df_NYC %>% filter(Zip%in% c(10029, 10035))
  df_East_Harlem$Neighborhood <- "EAST HARLEM"

df_Gramercy_Park_Murray_Hill <- df_NYC %>% filter(Zip%in% c(10010, 10016, 10017, 10022))
  df_Gramercy_Park_Murray_Hill$Neighborhood <- "GRAMERCY PARK AND MURRAY HILL"

df_Greenwich_Village_SoHo <- df_NYC %>% filter(Zip%in% c(10012, 10013, 10014))
  df_Greenwich_Village_SoHo$Neighborhood <- "GREENWICH VILLAGE AND SOHO"

df_Lower_Manhattan <- df_NYC %>% filter(Zip%in% c(10004, 10005, 10006, 10007, 10038, 10280))
  df_Lower_Manhattan$Neighborhood <- "LOWER MANHATTAN"

df_Lower_East <- df_NYC %>% filter(Zip%in% c(10002, 10003, 10009))
  df_Lower_East$Neighborhood <- "LOWER EAST SIDE"
  
df_Upper_East <- df_NYC %>% filter(Zip%in% c(10021, 10028, 10044, 10065, 10075, 10128))
  df_Upper_East$Neighborhood <- "UPPER EAST SIDE"
  
df_Upper_West <- df_NYC %>% filter(Zip%in% c(10023, 10024, 10025))
  df_Upper_West$Neighborhood <- "UPPER WEST SIDE"
  
df_Inwood_Washington_Heights <- df_NYC %>% filter(Zip%in% c(10031, 10032, 10033, 10034, 10040))
  df_Inwood_Washington_Heights$Neighborhood <- "INWOOD AND WASHINGTON HEIGHTS"

df_Manhattan <- rbind(df_Central_Harlem, df_Chelsea_Clinton, df_East_Harlem, df_Gramercy_Park_Murray_Hill, df_Greenwich_Village_SoHo, df_Lower_Manhattan, df_Lower_East, df_Upper_East , df_Upper_West , df_Inwood_Washington_Heights)

```

```{r calls Queens}

df_Northeast_Queens <- df_NYC %>% filter(Zip%in% c(11361, 11362, 11363, 11364))
  df_Northeast_Queens$Neighborhood <- "NORTHEAST QUEENS"

df_North_Queens <- df_NYC %>% filter(Zip%in% c(11354, 11355, 11356, 11357, 11358, 11359, 11360))
  df_North_Queens$Neighborhood <- "NORTH QUEENS"

df_Central_Queens <- df_NYC %>% filter(Zip%in% c(11365, 11366, 11367))
  df_Central_Queens$Neighborhood <- "CENTRAL QUEENS"

df_Jamaica <- df_NYC %>% filter(Zip%in% c(11412, 11423, 11432, 11433, 11434, 11435, 11436))
  df_Jamaica$Neighborhood <- "JAMAICA"

df_Northwest_Queens <- df_NYC %>% filter(Zip%in% c(11101, 11102, 11103, 11104, 11105, 11106))
  df_Northwest_Queens$Neighborhood <- "NORTHWEST QUEENS"

df_West_Central_Queens <- df_NYC %>% filter(Zip%in% c(11374, 11375, 11379, 11385))
  df_West_Central_Queens$Neighborhood <- "WEST CENTRAL QUEENS"

df_Rockaways <- df_NYC %>% filter(Zip%in% c(11691, 11692, 11693, 11694, 11697))
  df_Rockaways$Neighborhood <- "ROCKAWAYS"
  
df_Southeast_Queens <- df_NYC %>% filter(Zip%in% c(11004, 11005, 11411, 11413, 11422, 11426, 11427, 11428, 11429))
  df_Southeast_Queens$Neighborhood <- "SOUTHEAST QUEENS"

df_Southwest_Queens <- df_NYC %>% filter(Zip%in% c(11414, 11415, 11416, 11417, 11418, 11419, 11420, 11421))
  df_Southwest_Queens$Neighborhood <- "SOUTHWEST QUEENS"

df_West_Queens <- df_NYC %>% filter(Zip%in% c(11368, 11369, 11370, 11372, 11373, 11377, 11378))
  df_West_Queens$Neighborhood <- "WEST QUEENS"

df_Queens <- rbind(df_Northeast_Queens, df_North_Queens, df_Central_Queens, df_Jamaica, df_Northwest_Queens, df_West_Central_Queens, df_Rockaways, df_Southeast_Queens, df_Southwest_Queens, df_West_Queens)

```

```{r calls Staten Island}

df_Port_Richmond <- df_NYC %>% filter(Zip%in% c(10302, 10303, 10310))
  df_Port_Richmond$Neighborhood <- "PORT RICHMOND"

df_South_Shore <- df_NYC %>% filter(Zip%in% c(10306, 10307, 10308, 10309, 10312))
  df_South_Shore$Neighborhood <- "SOUTH SHORE"

df_Stapleton_StGeorge <- df_NYC %>% filter(Zip%in% c(10301, 10304, 10305))
  df_Stapleton_StGeorge$Neighborhood <- "STAPLETON AND ST. GEORGE"

df_MidIsland <- df_NYC %>% filter(Zip%in% c(10314))
  df_MidIsland$Neighborhood <- "MID ISLAND"

df_Staten_Island <- rbind(df_Port_Richmond, df_South_Shore, df_Stapleton_StGeorge, df_MidIsland)

```

```{r calls NYC}

df_NYC <- rbind(df_The_Bronx, df_Brooklyn, df_Manhattan, df_Queens, df_Staten_Island)
write.csv(df_NYC, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_NYC.csv", row.names=FALSE)

```

```{r calls}
write.csv(df_The_Bronx, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_The_Bronx.csv", row.names=FALSE)

write.csv(df_Brooklyn, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_Brooklyn.csv", row.names=FALSE)

write.csv(df_Manhattan, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_Manhattan.csv", row.names=FALSE)

write.csv(df_Queens, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_Queens.csv", row.names=FALSE)

write.csv(df_Staten_Island, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_Staten_Island.csv", row.names=FALSE)

```

```{r Bronx}
capture_recapture_the_bronx <- function(year) {
  lots_year_1 <- df_The_Bronx %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_The_Bronx %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_The_Bronx_Num_Rats <- sapply(2011:2021, capture_recapture_the_bronx)
df_The_Bronx_Num_Rats <- as.data.frame(df_The_Bronx_Num_Rats)

df_The_Bronx_Num_Rats <- df_The_Bronx_Num_Rats %>%
  add_column(Borough = "BRONX",
             .after = "df_The_Bronx_Num_Rats") 
  
df_The_Bronx_Num_Rats <- df_The_Bronx_Num_Rats %>%
  add_column(Year = 2011:2021,
             .after = "Borough") 

df_The_Bronx_Num_Rats <- rename(df_The_Bronx_Num_Rats, numRats = df_The_Bronx_Num_Rats)
```

```{r Brooklyn}
capture_recapture_brooklyn <- function(year) {
  lots_year_1 <- df_Brooklyn %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Brooklyn %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Brooklyn_Num_Rats <- sapply(2011:2021, capture_recapture_brooklyn)
df_Brooklyn_Num_Rats <- as.data.frame(df_Brooklyn_Num_Rats)

df_Brooklyn_Num_Rats <- df_Brooklyn_Num_Rats %>%
  add_column(Borough = "BROOKLYN",
             .after = "df_Brooklyn_Num_Rats") 
  
df_Brooklyn_Num_Rats <- df_Brooklyn_Num_Rats %>%
  add_column(Year = 2011:2021,
             .after = "Borough") 

df_Brooklyn_Num_Rats <- rename(df_Brooklyn_Num_Rats, numRats = df_Brooklyn_Num_Rats)
```

```{r Manhattan}
capture_recapture_manhattan <- function(year) {
  lots_year_1 <- df_Manhattan %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Manhattan %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Manhattan_Num_Rats <- sapply(2011:2021, capture_recapture_manhattan)
df_Manhattan_Num_Rats <- as.data.frame(df_Manhattan_Num_Rats)

df_Manhattan_Num_Rats <- df_Manhattan_Num_Rats %>%
  add_column(Borough = "MANHATTAN",
             .after = "df_Manhattan_Num_Rats") 
  
df_Manhattan_Num_Rats <- df_Manhattan_Num_Rats %>%
  add_column(Year = 2011:2021,
             .after = "Borough") 

df_Manhattan_Num_Rats <- rename(df_Manhattan_Num_Rats, numRats = df_Manhattan_Num_Rats)
```

```{r Queens}
capture_recapture_queens <- function(year) {
  lots_year_1 <- df_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Queens_Num_Rats <- sapply(2011:2021, capture_recapture_queens)
df_Queens_Num_Rats <- as.data.frame(df_Queens_Num_Rats)

df_Queens_Num_Rats <- df_Queens_Num_Rats %>%
  add_column(Borough = "QUEENS",
             .after = "df_Queens_Num_Rats") 
  
df_Queens_Num_Rats <- df_Queens_Num_Rats %>%
  add_column(Year = 2011:2021,
             .after = "Borough") 

df_Queens_Num_Rats <- rename(df_Queens_Num_Rats, numRats = df_Queens_Num_Rats)
```

```{r Staten Island}
capture_recapture_staten_island <- function(year) {
  lots_year_1 <- df_Staten_Island %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Staten_Island %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Staten_Island_Num_Rats <- sapply(2011:2021, capture_recapture_staten_island) #turns to a list of 7
df_Staten_Island_Num_Rats <- as.data.frame(df_Staten_Island_Num_Rats)

df_Staten_Island_Num_Rats <- df_Staten_Island_Num_Rats %>%  #adding in Borough manually
  add_column(Borough = "STATEN ISLAND",
             .after = "df_Staten_Island_Num_Rats")
  
df_Staten_Island_Num_Rats <- df_Staten_Island_Num_Rats %>%
  add_column(Year = 2011:2021,
             .after = "Borough") 

df_Staten_Island_Num_Rats <- rename(df_Staten_Island_Num_Rats, numRats = df_Staten_Island_Num_Rats)
```

```{r Cumulative}

options(scipen = 999)

df_NYC_Num_Rats <- list( df_Brooklyn_Num_Rats, df_Queens_Num_Rats,  df_Manhattan_Num_Rats, df_The_Bronx_Num_Rats, df_Staten_Island_Num_Rats)

df_NYC_Num_Rats <- Reduce(function(x,y) merge(x,y, all = TRUE), df_NYC_Num_Rats)

df_NYC_Num_Rats <- df_NYC_Num_Rats[order(df_NYC_Num_Rats$numRats),]

graph1.static <- ggplot(df_NYC_Num_Rats, aes(x = Year, y = numRats, color = Borough)) +
   geom_line(size = 1.5) +
   scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
   scale_y_continuous(breaks = seq(0,1500000, by = 100000)) +
   labs (title = "Rat Population In Each Borough Over Time", subtitle = "(Capture-Recapture by Borough)", x = "Year", y = "Population" ) +
   theme_fivethirtyeight() +
   theme(axis.title = element_text())

ggsave("graph1v2.png", height = 1600, width = 2560, units = "px")

graph2.static <- ggplot(df_NYC_Num_Rats, aes(x = Year, y = numRats, fill = Borough)) +
  geom_area(alpha=0.725) +
  scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
  scale_y_continuous(breaks = seq(0,4000000, by = 250000)) +
  labs (title = "Rat Population In NYC", x = "Year", y = "Population" ) +
  theme_fivethirtyeight() +
  theme(axis.title.y = element_text(), axis.title.x = element_text())

ggsave("graph2.png", height = 1600, width = 2560, units = "px")

graph1.anim <- ggplot(df_NYC_Num_Rats, aes(x = Year, y = numRats, color = Borough)) +
   geom_line(size = 1.5) +
   scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
   scale_y_continuous(breaks = seq(0,1500000, by = 100000)) +
   labs (title = "Do Rats Proliferate Faster in Certain Boroughs?", subtitle = "Year: {frame_along}", x = "Year", y = "Population" ) +
   theme_fivethirtyeight() +
   theme(axis.title = element_text()) +
   theme(axis.title.y = element_text(), axis.title.x = element_text()) +
   transition_reveal(Year) +
   view_follow()

animate(graph1.anim, height = 1000, width = 1600, fps = 30, duration = 15, end_pause = 90, res = 100)
anim_save("graph1anim.gif")

graph2.anim <- ggplot(df_NYC_Num_Rats, aes(x = Year, y = numRats, fill = Borough)) +
   geom_area(alpha=0.725) +
   scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
   scale_y_continuous(breaks = seq(0,4000000, by = 250000)) +
   labs (title = "Rat Population In NYC", subtitle = "(Capture-Recapture by Borough)", x = "Year", y = "Population" ) +
   theme_fivethirtyeight() +
   theme(axis.title.y = element_text(), axis.title.x = element_text()) +
   transition_reveal(Year) +
   view_follow()

animate(graph2.anim, height = 1000, width = 1600, fps = 30, duration = 15, end_pause = 90, res = 100)
anim_save("graph2animv2.gif")

```

```{r Bronx Neighborhoods}

capture_recapture_the_bronx_n <- function(year) {
  lots_year_1 <- df_Central_Bronx %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Central_Bronx %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Central_Bronx <- sapply(2011:2021, capture_recapture_the_bronx_n)
df_Central_Bronx <- as.data.frame(df_Central_Bronx)

df_Central_Bronx <- df_Central_Bronx %>%
  add_column(Neighborhood = "CENTRAL BRONX",
             .after = "df_Central_Bronx") 
  
df_Central_Bronx <- df_Central_Bronx %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Central_Bronx <- rename(df_Central_Bronx, numRats = df_Central_Bronx)

capture_recapture_the_bronx_n <- function(year) {
  lots_year_1 <- df_Bronx_Park_Fordham %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Bronx_Park_Fordham %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Bronx_Park_Fordham <- sapply(2011:2021, capture_recapture_the_bronx_n)
df_Bronx_Park_Fordham <- as.data.frame(df_Bronx_Park_Fordham)

df_Bronx_Park_Fordham <- df_Bronx_Park_Fordham %>%
  add_column(Neighborhood = "BRONX PARK AND FORDHAM",
             .after = "df_Bronx_Park_Fordham") 
  
df_Bronx_Park_Fordham <- df_Bronx_Park_Fordham %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Bronx_Park_Fordham <- rename(df_Bronx_Park_Fordham, numRats = df_Bronx_Park_Fordham)

capture_recapture_the_bronx_n <- function(year) {
  lots_year_1 <- df_High_Bridge_Morrisania %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_High_Bridge_Morrisania %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_High_Bridge_Morrisania <- sapply(2011:2021, capture_recapture_the_bronx_n)
df_High_Bridge_Morrisania <- as.data.frame(df_High_Bridge_Morrisania)

df_High_Bridge_Morrisania <- df_High_Bridge_Morrisania %>%
  add_column(Neighborhood = "HIGH BRIDGE AND MORRISANIA",
             .after = "df_High_Bridge_Morrisania") 
  
df_High_Bridge_Morrisania <- df_High_Bridge_Morrisania %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_High_Bridge_Morrisania <- rename(df_High_Bridge_Morrisania, numRats = df_High_Bridge_Morrisania)

capture_recapture_the_bronx_n <- function(year) {
  lots_year_1 <- df_Hunts_Point_Mott_Haven %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Hunts_Point_Mott_Haven %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Hunts_Point_Mott_Haven <- sapply(2011:2021, capture_recapture_the_bronx_n)
df_Hunts_Point_Mott_Haven <- as.data.frame(df_Hunts_Point_Mott_Haven)

df_Hunts_Point_Mott_Haven <- df_Hunts_Point_Mott_Haven %>%
  add_column(Neighborhood = "HUNTS POINT AND MOTT HAVEN",
             .after = "df_Hunts_Point_Mott_Haven") 
  
df_Hunts_Point_Mott_Haven <- df_Hunts_Point_Mott_Haven %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Hunts_Point_Mott_Haven <- rename(df_Hunts_Point_Mott_Haven, numRats = df_Hunts_Point_Mott_Haven)


capture_recapture_the_bronx_n <- function(year) {
  lots_year_1 <- df_Kingsbridge_Riverdale %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Kingsbridge_Riverdale %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Kingsbridge_Riverdale <- sapply(2011:2021, capture_recapture_the_bronx_n)
df_Kingsbridge_Riverdale <- as.data.frame(df_Kingsbridge_Riverdale)

df_Kingsbridge_Riverdale <- df_Kingsbridge_Riverdale %>%
  add_column(Neighborhood = "KINGSBRIDGE AND RIVERDALE",
             .after = "df_Kingsbridge_Riverdale") 
  
df_Kingsbridge_Riverdale <- df_Kingsbridge_Riverdale %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Kingsbridge_Riverdale <- rename(df_Kingsbridge_Riverdale, numRats = df_Kingsbridge_Riverdale)

capture_recapture_the_bronx_n <- function(year) {
  lots_year_1 <- df_Northeast_Bronx %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Northeast_Bronx %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Northeast_Bronx <- sapply(2011:2021, capture_recapture_the_bronx_n)
df_Northeast_Bronx <- as.data.frame(df_Northeast_Bronx)

df_Northeast_Bronx <- df_Northeast_Bronx %>%
  add_column(Neighborhood = "NORTHEAST BRONX",
             .after = "df_Northeast_Bronx") 
  
df_Northeast_Bronx <- df_Northeast_Bronx %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Northeast_Bronx <- rename(df_Northeast_Bronx, numRats = df_Northeast_Bronx)

capture_recapture_the_bronx_n <- function(year) {
  lots_year_1 <- df_Southeast_Bronx %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Southeast_Bronx %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Southeast_Bronx <- sapply(2011:2021, capture_recapture_the_bronx_n)
df_Southeast_Bronx <- as.data.frame(df_Southeast_Bronx)

df_Southeast_Bronx <- df_Southeast_Bronx %>%
  add_column(Neighborhood = "SOUTHEAST BRONX",
             .after = "df_Southeast_Bronx") 
  
df_Southeast_Bronx <- df_Southeast_Bronx %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Southeast_Bronx <- rename(df_Southeast_Bronx, numRats = df_Southeast_Bronx)

df_The_Bronx_Neighborhood_Rats <- rbind(df_Central_Bronx, df_Bronx_Park_Fordham, df_High_Bridge_Morrisania, df_Hunts_Point_Mott_Haven, df_Kingsbridge_Riverdale, df_Northeast_Bronx, df_Southeast_Bronx)

rm(df_Central_Bronx, df_Bronx_Park_Fordham, df_High_Bridge_Morrisania, df_Hunts_Point_Mott_Haven, df_Kingsbridge_Riverdale, df_Northeast_Bronx, df_Southeast_Bronx)

graphBronxTotal.static <- ggplot(df_The_Bronx_Neighborhood_Rats, aes(x = Year, y = numRats, color = Neighborhood)) +
  geom_line(size = 1.5, aes(alpha = Neighborhood)) +
  scale_alpha_manual(values=c(0.3,0.3,0.3,0.3,1,0.3,1)) +
  scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
  scale_y_continuous(breaks = seq(0,350000, by = 50000)) +
  labs (title = "Rat Population In Each Borough Over Time", subtitle = "Do rats proliferate faster in certain Boroughs?", x = "Year", y = "Population" ) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) 

ggsave("graphBronxTotalN.png", height = 2400, width = 3840, units = "px")

```

```{r Brooklyn Neighborhoods}

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Central_Brooklyn %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Central_Brooklyn %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Central_Brooklyn <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Central_Brooklyn <- as.data.frame(df_Central_Brooklyn)

df_Central_Brooklyn <- df_Central_Brooklyn %>%
  add_column(Neighborhood = "CENTRAL BROOKLYN",
             .after = "df_Central_Brooklyn") 
  
df_Central_Brooklyn <- df_Central_Brooklyn %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Central_Brooklyn <- rename(df_Central_Brooklyn, numRats = df_Central_Brooklyn)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Southwest_Brooklyn %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Southwest_Brooklyn %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Southwest_Brooklyn <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Southwest_Brooklyn <- as.data.frame(df_Southwest_Brooklyn)

df_Southwest_Brooklyn <- df_Southwest_Brooklyn %>%
  add_column(Neighborhood = "SOUTHWEST BROOKLYN",
             .after = "df_Southwest_Brooklyn") 
  
df_Southwest_Brooklyn <- df_Southwest_Brooklyn %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Southwest_Brooklyn <- rename(df_Southwest_Brooklyn, numRats = df_Southwest_Brooklyn)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Borough_Park %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Borough_Park %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Borough_Park <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Borough_Park <- as.data.frame(df_Borough_Park)

df_Borough_Park <- df_Borough_Park %>%
  add_column(Neighborhood = "BOROUGH PARK",
             .after = "df_Borough_Park") 
  
df_Borough_Park <- df_Borough_Park %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Borough_Park <- rename(df_Borough_Park, numRats = df_Borough_Park)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Canarsie_Flatlands %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Canarsie_Flatlands %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Canarsie_Flatlands <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Canarsie_Flatlands <- as.data.frame(df_Canarsie_Flatlands)

df_Canarsie_Flatlands <- df_Canarsie_Flatlands %>%
  add_column(Neighborhood = "CANARSIE AND FLATLANDS",
             .after = "df_Canarsie_Flatlands") 
  
df_Canarsie_Flatlands <- df_Canarsie_Flatlands %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Canarsie_Flatlands <- rename(df_Canarsie_Flatlands, numRats = df_Canarsie_Flatlands)


capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Southern_Brooklyn %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Southern_Brooklyn %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Southern_Brooklyn <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Southern_Brooklyn <- as.data.frame(df_Southern_Brooklyn)

df_Southern_Brooklyn <- df_Southern_Brooklyn %>%
  add_column(Neighborhood = "SOUTHERN BROOKLYN",
             .after = "df_Southern_Brooklyn") 
  
df_Southern_Brooklyn <- df_Southern_Brooklyn %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Southern_Brooklyn <- rename(df_Southern_Brooklyn, numRats = df_Southern_Brooklyn)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Northwest_Brooklyn %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Northwest_Brooklyn %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Northwest_Brooklyn <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Northwest_Brooklyn <- as.data.frame(df_Northwest_Brooklyn)

df_Northwest_Brooklyn <- df_Northwest_Brooklyn %>%
  add_column(Neighborhood = "NORTHWEST BROOKLYN",
             .after = "df_Northwest_Brooklyn") 
  
df_Northwest_Brooklyn <- df_Northwest_Brooklyn %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Northwest_Brooklyn <- rename(df_Northwest_Brooklyn, numRats = df_Northwest_Brooklyn)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Flatbush %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Flatbush %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Flatbush <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Flatbush <- as.data.frame(df_Flatbush)

df_Flatbush <- df_Flatbush %>%
  add_column(Neighborhood = "FLATBUSH",
             .after = "df_Flatbush") 
  
df_Flatbush <- df_Flatbush %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Flatbush <- rename(df_Flatbush, numRats = df_Flatbush)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_East_NY_New_Lots %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_East_NY_New_Lots %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_East_NY_New_Lots <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_East_NY_New_Lots <- as.data.frame(df_East_NY_New_Lots)

df_East_NY_New_Lots <- df_East_NY_New_Lots %>%
  add_column(Neighborhood = "EAST NEW YORK AND NEW LOTS",
             .after = "df_East_NY_New_Lots") 
  
df_East_NY_New_Lots <- df_East_NY_New_Lots %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_East_NY_New_Lots <- rename(df_East_NY_New_Lots, numRats = df_East_NY_New_Lots)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Greenpoint %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Greenpoint %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Greenpoint <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Greenpoint <- as.data.frame(df_Greenpoint)

df_Greenpoint <- df_Greenpoint %>%
  add_column(Neighborhood = "GREENPOINT",
             .after = "df_Greenpoint") 
  
df_Greenpoint <- df_Greenpoint %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Greenpoint <- rename(df_Greenpoint, numRats = df_Greenpoint)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Sunset_Park %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Sunset_Park %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Sunset_Park <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Sunset_Park <- as.data.frame(df_Sunset_Park)

df_Sunset_Park <- df_Sunset_Park %>%
  add_column(Neighborhood = "SUNSET PARK",
             .after = "df_Sunset_Park") 
  
df_Sunset_Park <- df_Sunset_Park %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Sunset_Park <- rename(df_Sunset_Park, numRats = df_Sunset_Park)

capture_recapture_brooklyn_n <- function(year) {
  lots_year_1 <- df_Bushwick_Williamsburg %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Bushwick_Williamsburg %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Bushwick_Williamsburg <- sapply(2011:2021, capture_recapture_brooklyn_n)
df_Bushwick_Williamsburg <- as.data.frame(df_Bushwick_Williamsburg)

df_Bushwick_Williamsburg <- df_Bushwick_Williamsburg %>%
  add_column(Neighborhood = "BUSHWICK AND WILLIAMSBURG",
             .after = "df_Bushwick_Williamsburg") 
  
df_Bushwick_Williamsburg <- df_Bushwick_Williamsburg %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Bushwick_Williamsburg <- rename(df_Bushwick_Williamsburg, numRats = df_Bushwick_Williamsburg)

df_Brooklyn_Neighborhood_Rats <- rbind(df_Central_Brooklyn, df_Southwest_Brooklyn, df_Borough_Park, df_Canarsie_Flatlands, df_Southern_Brooklyn, df_Northwest_Brooklyn, df_Flatbush, df_East_NY_New_Lots, df_Greenpoint, df_Bushwick_Williamsburg, df_Sunset_Park)

rm(df_Central_Brooklyn, df_Southwest_Brooklyn, df_Borough_Park, df_Canarsie_Flatlands, df_Southern_Brooklyn, df_Northwest_Brooklyn, df_Flatbush, df_East_NY_New_Lots, df_Greenpoint, df_Bushwick_Williamsburg, df_Sunset_Park)

graphBrooklynTotal.static <- ggplot(df_Brooklyn_Neighborhood_Rats, aes(x = Year, y = numRats, color = Neighborhood)) +
  geom_line(size = 1.5, aes(alpha = Neighborhood)) +
  scale_alpha_manual(values=c(0.3,1,1,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3)) +
  scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
  scale_y_continuous(breaks = seq(0,350000, by = 50000)) +
  labs (title = "Rat Population In Each Borough Over Time", subtitle = "Do rats proliferate faster in certain Boroughs?", x = "Year", y = "Population" ) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) 

ggsave("graphBrooklynTotalN.png", height = 2400, width = 3840, units = "px")

```

```{r Manhattan Neighborhoods}

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Central_Harlem %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Central_Harlem %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Central_Harlem <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Central_Harlem <- as.data.frame(df_Central_Harlem)

df_Central_Harlem <- df_Central_Harlem %>%
  add_column(Neighborhood = "CENTRAL HARLEM",
             .after = "df_Central_Harlem") 
  
df_Central_Harlem <- df_Central_Harlem %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Central_Harlem <- rename(df_Central_Harlem, numRats = df_Central_Harlem)

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Chelsea_Clinton %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Chelsea_Clinton %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Chelsea_Clinton <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Chelsea_Clinton <- as.data.frame(df_Chelsea_Clinton)

df_Chelsea_Clinton <- df_Chelsea_Clinton %>%
  add_column(Neighborhood = "CHELSEA AND CLINTON",
             .after = "df_Chelsea_Clinton") 
  
df_Chelsea_Clinton <- df_Chelsea_Clinton %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Chelsea_Clinton <- rename(df_Chelsea_Clinton, numRats = df_Chelsea_Clinton)

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_East_Harlem %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_East_Harlem %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_East_Harlem <- sapply(2011:2021, capture_recapture_manhattan_n)
df_East_Harlem <- as.data.frame(df_East_Harlem)

df_East_Harlem <- df_East_Harlem %>%
  add_column(Neighborhood = "EAST HARLEM",
             .after = "df_East_Harlem") 
  
df_East_Harlem <- df_East_Harlem %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_East_Harlem <- rename(df_East_Harlem, numRats = df_East_Harlem)

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Gramercy_Park_Murray_Hill %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Gramercy_Park_Murray_Hill %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Gramercy_Park_Murray_Hill <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Gramercy_Park_Murray_Hill <- as.data.frame(df_Gramercy_Park_Murray_Hill)

df_Gramercy_Park_Murray_Hill <- df_Gramercy_Park_Murray_Hill %>%
  add_column(Neighborhood = "GRAMERCY PARK AND MURRAY HILL",
             .after = "df_Gramercy_Park_Murray_Hill") 
  
df_Gramercy_Park_Murray_Hill <- df_Gramercy_Park_Murray_Hill %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Gramercy_Park_Murray_Hill <- rename(df_Gramercy_Park_Murray_Hill, numRats = df_Gramercy_Park_Murray_Hill)


capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Greenwich_Village_SoHo %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Greenwich_Village_SoHo %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Greenwich_Village_SoHo <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Greenwich_Village_SoHo <- as.data.frame(df_Greenwich_Village_SoHo)

df_Greenwich_Village_SoHo <- df_Greenwich_Village_SoHo %>%
  add_column(Neighborhood = "GREENWICH VILLAGE AND SOHO",
             .after = "df_Greenwich_Village_SoHo") 
  
df_Greenwich_Village_SoHo <- df_Greenwich_Village_SoHo %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Greenwich_Village_SoHo <- rename(df_Greenwich_Village_SoHo, numRats = df_Greenwich_Village_SoHo)

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Lower_Manhattan %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Lower_Manhattan %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Lower_Manhattan <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Lower_Manhattan <- as.data.frame(df_Lower_Manhattan)

df_Lower_Manhattan <- df_Lower_Manhattan %>%
  add_column(Neighborhood = "LOWER MANHATTAN",
             .after = "df_Lower_Manhattan") 
  
df_Lower_Manhattan <- df_Lower_Manhattan %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Lower_Manhattan <- rename(df_Lower_Manhattan, numRats = df_Lower_Manhattan)

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Lower_East %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Lower_East %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Lower_East <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Lower_East <- as.data.frame(df_Lower_East)

df_Lower_East <- df_Lower_East %>%
  add_column(Neighborhood = "LOWER EAST SIDE",
             .after = "df_Lower_East") 
  
df_Lower_East <- df_Lower_East %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Lower_East <- rename(df_Lower_East, numRats = df_Lower_East)

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Upper_East %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Upper_East %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Upper_East <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Upper_East <- as.data.frame(df_Upper_East)

df_Upper_East <- df_Upper_East %>%
  add_column(Neighborhood = "UPPER EAST SIDE",
             .after = "df_Upper_East") 
  
df_Upper_East <- df_Upper_East %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Upper_East <- rename(df_Upper_East, numRats = df_Upper_East)

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Upper_West %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Upper_West %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Upper_West <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Upper_West <- as.data.frame(df_Upper_West)

df_Upper_West <- df_Upper_West %>%
  add_column(Neighborhood = "UPPER WEST SIDE",
             .after = "df_Upper_West") 
  
df_Upper_West <- df_Upper_West %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Upper_West <- rename(df_Upper_West, numRats = df_Upper_West)

capture_recapture_manhattan_n <- function(year) {
  lots_year_1 <- df_Inwood_Washington_Heights %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Inwood_Washington_Heights %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Inwood_Washington_Heights <- sapply(2011:2021, capture_recapture_manhattan_n)
df_Inwood_Washington_Heights <- as.data.frame(df_Inwood_Washington_Heights)

df_Inwood_Washington_Heights <- df_Inwood_Washington_Heights %>%
  add_column(Neighborhood = "INWOOD AND WASHINGTON HEIGHTS",
             .after = "df_Inwood_Washington_Heights") 
  
df_Inwood_Washington_Heights <- df_Inwood_Washington_Heights %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Inwood_Washington_Heights <- rename(df_Inwood_Washington_Heights, numRats = df_Inwood_Washington_Heights)

df_Manhattan_Neighborhood_Rats <- rbind(df_Central_Harlem, df_Chelsea_Clinton, df_East_Harlem, df_Gramercy_Park_Murray_Hill, df_Greenwich_Village_SoHo, df_Lower_Manhattan, df_Lower_East, df_Upper_East, df_Upper_West, df_Inwood_Washington_Heights)

rm(df_Central_Harlem, df_Chelsea_Clinton, df_East_Harlem, df_Gramercy_Park_Murray_Hill, df_Greenwich_Village_SoHo, df_Lower_Manhattan, df_Lower_East, df_Upper_East, df_Upper_West, df_Inwood_Washington_Heights)

graphManhattanTotal.static <- ggplot(df_Manhattan_Neighborhood_Rats, aes(x = Year, y = numRats, color = Neighborhood)) +
  geom_line(size = 1.5, aes(alpha = Neighborhood)) +
  scale_alpha_manual(values=c(0.3,1,0.3,0.3,1,0.3,0.3,0.3,0.3,0.3)) +
  scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
  scale_y_continuous(breaks = seq(0,350000, by = 50000)) +
  labs (title = "Rat Population In Each Borough Over Time", subtitle = "Do rats proliferate faster in certain Boroughs?", x = "Year", y = "Population" ) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) 

ggsave("graphManhattanTotalN.png", height = 2400, width = 3840, units = "px")

```

```{r Queens Neighborhoods}

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_Northeast_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Northeast_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Northeast_Queens <- sapply(2011:2021, capture_recapture_queens_n)
df_Northeast_Queens <- as.data.frame(df_Northeast_Queens)

df_Northeast_Queens <- df_Northeast_Queens %>%
  add_column(Neighborhood = "NORTHEAST QUEENS",
             .after = "df_Northeast_Queens") 
  
df_Northeast_Queens <- df_Northeast_Queens %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Northeast_Queens <- rename(df_Northeast_Queens, numRats = df_Northeast_Queens)

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_North_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_North_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_North_Queens <- sapply(2011:2021, capture_recapture_queens_n)
df_North_Queens <- as.data.frame(df_North_Queens)

df_North_Queens <- df_North_Queens %>%
  add_column(Neighborhood = "NORTH QUEENS",
             .after = "df_North_Queens") 
  
df_North_Queens <- df_North_Queens %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_North_Queens <- rename(df_North_Queens, numRats = df_North_Queens)

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_Central_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Central_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Central_Queens <- sapply(2011:2021, capture_recapture_queens_n)
df_Central_Queens <- as.data.frame(df_Central_Queens)

df_Central_Queens <- df_Central_Queens %>%
  add_column(Neighborhood = "CENTRAL QUEENS",
             .after = "df_Central_Queens") 
  
df_Central_Queens <- df_Central_Queens %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Central_Queens <- rename(df_Central_Queens, numRats = df_Central_Queens)

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_Jamaica %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Jamaica %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Jamaica <- sapply(2011:2021, capture_recapture_queens_n)
df_Jamaica <- as.data.frame(df_Jamaica)

df_Jamaica <- df_Jamaica %>%
  add_column(Neighborhood = "JAMAICA",
             .after = "df_Jamaica") 
  
df_Jamaica <- df_Jamaica %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Jamaica <- rename(df_Jamaica, numRats = df_Jamaica)


capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_Northwest_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Northwest_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Northwest_Queens <- sapply(2011:2021, capture_recapture_queens_n)
df_Northwest_Queens <- as.data.frame(df_Northwest_Queens)

df_Northwest_Queens <- df_Northwest_Queens %>%
  add_column(Neighborhood = "NORTHWEST QUEENS",
             .after = "df_Northwest_Queens") 
  
df_Northwest_Queens <- df_Northwest_Queens %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Northwest_Queens <- rename(df_Northwest_Queens, numRats = df_Northwest_Queens)

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_West_Central_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_West_Central_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_West_Central_Queens <- sapply(2011:2021, capture_recapture_queens_n)
df_West_Central_Queens <- as.data.frame(df_West_Central_Queens)

df_West_Central_Queens <- df_West_Central_Queens %>%
  add_column(Neighborhood = "WEST CENTRAL QUEENS",
             .after = "df_West_Central_Queens") 
  
df_West_Central_Queens <- df_West_Central_Queens %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_West_Central_Queens <- rename(df_West_Central_Queens, numRats = df_West_Central_Queens)

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_Rockaways %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Rockaways %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Rockaways <- sapply(2011:2021, capture_recapture_queens_n)
df_Rockaways <- as.data.frame(df_Rockaways)

df_Rockaways <- df_Rockaways %>%
  add_column(Neighborhood = "ROCKAWAYS",
             .after = "df_Rockaways") 
  
df_Rockaways <- df_Rockaways %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Rockaways <- rename(df_Rockaways, numRats = df_Rockaways)

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_Southeast_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Southeast_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Southeast_Queens <- sapply(2011:2021, capture_recapture_queens_n)
df_Southeast_Queens <- as.data.frame(df_Southeast_Queens)

df_Southeast_Queens <- df_Southeast_Queens %>%
  add_column(Neighborhood = "SOUTHEAST QUEENS",
             .after = "df_Southeast_Queens") 
  
df_Southeast_Queens <- df_Southeast_Queens %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Southeast_Queens <- rename(df_Southeast_Queens, numRats = df_Southeast_Queens)

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_Southwest_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Southwest_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Southwest_Queens <- sapply(2011:2021, capture_recapture_queens_n)
df_Southwest_Queens <- as.data.frame(df_Southwest_Queens)

df_Southwest_Queens <- df_Southwest_Queens %>%
  add_column(Neighborhood = "SOUTHWEST QUEENS",
             .after = "df_Southwest_Queens") 
  
df_Southwest_Queens <- df_Southwest_Queens %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Southwest_Queens <- rename(df_Southwest_Queens, numRats = df_Southwest_Queens)

capture_recapture_queens_n <- function(year) {
  lots_year_1 <- df_West_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_West_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_West_Queens <- sapply(2011:2021, capture_recapture_queens_n)
df_West_Queens <- as.data.frame(df_West_Queens)

df_West_Queens <- df_West_Queens %>%
  add_column(Neighborhood = "WEST QUEENS",
             .after = "df_West_Queens") 
  
df_West_Queens <- df_West_Queens %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_West_Queens <- rename(df_West_Queens, numRats = df_West_Queens)

df_Queens_Neighborhood_Rats <- rbind(df_Northeast_Queens, df_North_Queens, df_Central_Queens, df_Jamaica, df_Northwest_Queens, df_West_Central_Queens, df_Rockaways, df_Southeast_Queens, df_Southwest_Queens, df_West_Queens)

rm(df_Northeast_Queens, df_North_Queens, df_Central_Queens, df_Jamaica, df_Northwest_Queens, df_West_Central_Queens, df_Rockaways, df_Southeast_Queens, df_Southwest_Queens, df_West_Queens)

graphQueensTotal.static <- ggplot(df_Queens_Neighborhood_Rats, aes(x = Year, y = numRats, color = Neighborhood)) +
  geom_line(size = 1.5, aes(alpha = Neighborhood)) +
  scale_alpha_manual(values=c(1,0.3,0.3,1,0.3,1,1,0.3,0.3,0.3)) +
  scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
  scale_y_continuous(breaks = seq(0,400000, by = 50000)) +
  labs (title = "Rat Population In Each Borough Over Time", subtitle = "Do rats proliferate faster in certain Boroughs?", x = "Year", y = "Population" ) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text())
  
ggsave("graphQueensTotalN.png", height = 2400, width = 3840, units = "px")

```

```{r Staten Island Neighborhoods}

capture_recapture_staten_island_n <- function(year) {
  lots_year_1 <- df_Port_Richmond %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Port_Richmond %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Port_Richmond <- sapply(2011:2021, capture_recapture_staten_island_n)
df_Port_Richmond <- as.data.frame(df_Port_Richmond)

df_Port_Richmond <- df_Port_Richmond %>%
  add_column(Neighborhood = "PORT RICHMOND",
             .after = "df_Port_Richmond") 
  
df_Port_Richmond <- df_Port_Richmond %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Port_Richmond <- rename(df_Port_Richmond, numRats = df_Port_Richmond)

capture_recapture_staten_island_n <- function(year) {
  lots_year_1 <- df_South_Shore %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_South_Shore %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_South_Shore <- sapply(2011:2021, capture_recapture_staten_island_n)
df_South_Shore <- as.data.frame(df_South_Shore)

df_South_Shore <- df_South_Shore %>%
  add_column(Neighborhood = "SOUTH SHORE",
             .after = "df_South_Shore") 
  
df_South_Shore <- df_South_Shore %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_South_Shore <- rename(df_South_Shore, numRats = df_South_Shore)

capture_recapture_staten_island_n <- function(year) {
  lots_year_1 <- df_Stapleton_StGeorge %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Stapleton_StGeorge %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Stapleton_StGeorge <- sapply(2011:2021, capture_recapture_staten_island_n)
df_Stapleton_StGeorge <- as.data.frame(df_Stapleton_StGeorge)

df_Stapleton_StGeorge <- df_Stapleton_StGeorge %>%
  add_column(Neighborhood = "STAPLETON AND ST. GEORGE",
             .after = "df_Stapleton_StGeorge") 
  
df_Stapleton_StGeorge <- df_Stapleton_StGeorge %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_Stapleton_StGeorge <- rename(df_Stapleton_StGeorge, numRats = df_Stapleton_StGeorge)

capture_recapture_staten_island_n <- function(year) {
  lots_year_1 <- df_MidIsland %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_MidIsland %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_MidIsland <- sapply(2011:2021, capture_recapture_staten_island_n)
df_MidIsland <- as.data.frame(df_MidIsland)

df_MidIsland <- df_MidIsland %>%
  add_column(Neighborhood = "MID ISLAND",
             .after = "df_MidIsland") 
  
df_MidIsland <- df_MidIsland %>%
  add_column(Year = 2011:2021,
             .after = "Neighborhood") 

df_MidIsland <- rename(df_MidIsland, numRats = df_MidIsland)

df_Staten_Island_Neighborhood_Rats <- rbind(df_Port_Richmond, df_South_Shore, df_Stapleton_StGeorge, df_MidIsland)

rm(df_Port_Richmond, df_South_Shore, df_Stapleton_StGeorge, df_MidIsland)

graphStatenTotal.static <- ggplot(df_Staten_Island_Neighborhood_Rats, aes(x = Year, y = numRats, color = Neighborhood)) +
  geom_line(size = 1.5) +
  scale_x_continuous(breaks = seq(2011,2021, by = 1)) +
  scale_y_continuous(breaks = seq(0,350000, by = 50000)) +
  labs (title = "Rat Population In Each Borough Over Time", subtitle = "Do rats proliferate faster in certain Boroughs?", x = "Year", y = "Population" ) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) 

ggsave("graphStatenTotalN.png", height = 2400, width = 3840, units = "px")

```

```{r Neighborhood Data Sets}

write.csv(df_The_Bronx_Neighborhood_Rats, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_The_Bronx_Neighborhoods.csv", row.names=FALSE)

write.csv(df_Brooklyn_Neighborhood_Rats, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_Brooklyn_Neighborhoods.csv", row.names=FALSE)

write.csv(df_Manhattan_Neighborhood_Rats, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_Manhattan_Neighborhoods.csv", row.names=FALSE)

write.csv(df_Queens_Neighborhood_Rats, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_Queens_Neighborhoods.csv", row.names=FALSE)

write.csv(df_Staten_Island_Neighborhood_Rats, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_Staten_Island_Neighborhoods.csv", row.names=FALSE)

```

```{r Rat per Capita and Rat per sqm}

nyc_capita_area <- read_csv("nyc_pop_zip_area_2020_by_neigborhood.csv")

nyc_neighborhoods_2020 <- rbind(df_The_Bronx_Neighborhood_Rats, df_Brooklyn_Neighborhood_Rats, df_Manhattan_Neighborhood_Rats, df_Queens_Neighborhood_Rats, df_Staten_Island_Neighborhood_Rats)

nyc_neighborhoods_2020 <- nyc_neighborhoods_2020 %>% filter(Year == 2020)

df_nyc_ratio_and_density <- merge(nyc_capita_area,nyc_neighborhoods_2020)

df_nyc_ratio_and_density <- df_nyc_ratio_and_density %>% mutate(human_rat_ratio = numRats/human_population)

df_nyc_ratio_and_density <- df_nyc_ratio_and_density %>% mutate(rats_per_sqm = numRats/square_meter)

write.csv(df_nyc_ratio_and_density, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\df_nyc_ratio_and_density.csv", row.names=FALSE)

mean(df_nyc_ratio_and_density$human_rat_ratio)
median(df_nyc_ratio_and_density$human_rat_ratio)

mean(df_nyc_ratio_and_density$rats_per_sqm)
median(df_nyc_ratio_and_density$rats_per_sqm)

ggplot(df_nyc_ratio_and_density,aes(x = rats_per_sqm, y = human_rat_ratio, color = Neighborhood)) + 
  geom_point() + 
  geom_label_repel(aes(label = Neighborhood),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50') +
  labs (title = "Rats Ratio 2020", subtitle = "How many Rats are there per person? How many Rats per square meter?", x = "Rat / Square Meter", y = "Rat-Human Ratio" ) + 
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) +
  theme(legend.position="none")

ggsave("graphNYCRatio.png", height = 3840, width = 3840, units = "px")

```

```{r violation Data Sets}

open_parking_violations <- read_csv("july_11_hydrant_violations.csv")

observed_violations <- read_csv("july_11_observations.csv")

result <- merge(open_parking_violations, observed_violations, by = "Plate")

write.csv(result, "C:\\Users\\Admin\\Desktop\\RatsData\\DataSets\\result.csv", row.names=FALSE)

```

```{r violation map}
install.packages("ggmap")

library("ggmap")

register_google("") #Insert API Key here

Manhattan_observed.map <- get_map(location= 'Manhattan, New York', 
                       maptype='roadmap', color='bw',source='google',zoom=12)
ggmap(Manhattan_observed.map) + 
  geom_point(observed_violations, color='red', size=2, mapping = aes(x=longdd, y=latdd)) +
  theme(axis.ticks = element_blank(), axis.text = element_blank()) +
  xlab('') + ylab('')

ggsave("observed_manhattan.png", height = 1920, width = 1920, units = "px")

Manhattan_ticketed.map <- get_map(location= 'Manhattan, New York', 
                       maptype='roadmap', color='bw',source='google',zoom=12)
ggmap(Manhattan_ticketed.map) + 
  geom_point(result, color='red', size=2, mapping = aes(x=longdd, y=latdd)) +
  theme(axis.ticks = element_blank(), axis.text = element_blank()) +
  xlab('') + ylab('')

ggsave("ticketed_manhattan.png", height = 1920, width = 1920, units = "px")
```
