---
title: "TestAppCapRecap"
author: "Chris"
date: '2022-06-20'
output: html_document
---

```{r}
install.packages("gganimate")
install.packages("gapminder")
install.packages("ggthemes")

library("tidyverse")
library("ggplot2")
library("gganimate")
library("dplyr")
library("gapminder")
library("ggthemes")
```

```{r}
calls <- read_csv("nyc_rodent_compliants.csv")
```

```{r}
 df <-
   calls %>%
   mutate(Date = as.Date(`Created Date`, format = "%m/%d/%Y"),
          Month_Year = format(Date, "%m/%y")) %>%
   filter(Descriptor == "Rat Sighting",
          Month_Year != 01/22, Month_Year >= 01/14) %>%
   select( BBL, Borough, `Incident Zip`, Month_Year) %>%
   na.omit() %>%
   group_by(BBL, Borough, `Incident Zip`, Month_Year) %>%
   summarize(count = n()) %>% 
   filter(BBL != 0, Borough > 10000)

df <- rename(df, Zip  = `Incident Zip` )
df <- separate(df, "Month_Year", c("Month","Year"), sep = "/")
df <- df[order(df$Year),]

write.csv(df, "C:\\Users\\Admin\\Desktop\\df_NYC.csv", row.names=FALSE)

df_NYC <- df
```

```{r}
lots_year_1 <- df %>% filter(Year == "14") %>% pull(BBL)
lots_year_2 <- df %>% filter(Year == "15") %>% pull(BBL)
number_in_year_1 <- length(lots_year_1)
number_in_year_2 <- length(lots_year_2)
number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  
number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
```

```{r}
50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
```

```{r}
capture_recapture <- function(year) {
  lots_year_1 <- df %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}
```

```{r}
qplot(x = factor(2011:2021),
      weight = sapply(11:21, capture_recapture),
      geom = "bar")  +
  labs(x = "year",
       y = "estimated rat population") +
  theme_bw()
```

```{r calls}
library(ggplot2)
ggplot(df, aes(fill= Borough, y = count , x = Year)) +
  geom_bar(position = "stack", stat = "identity") 
```

```{r replicating capture recapture but for dataframe not just an integer}
# lots_year_18 <- df %>% filter(Year == "18") %>% select(BBL, Borough, Zip)
# lots_year_19 <- df %>% filter(Year == "19") %>% select(BBL, Borough, Zip)
# 
# common_lots_18_19 <- inner_join(lots_year_18, lots_year_19)
```

```{r calls by borough}
df_The_Bronx <- df %>% filter(Borough == "BRONX")
df_Brooklyn <- df %>% filter(Borough == "BROOKLYN")
df_Manhattan <- df %>% filter(Borough == "MANHATTAN")
df_Queens <- df %>% filter(Borough == "QUEENS")
df_Staten_Island <- df %>% filter(Borough == "STATEN ISLAND")
```

```{r calls}
write.csv(df_The_Bronx, "C:\\Users\\Admin\\Desktop\\df_The_Bronx.csv", row.names=FALSE)

write.csv(df_Brooklyn, "C:\\Users\\Admin\\Desktop\\df_Brooklyn.csv", row.names=FALSE)

write.csv(df_Manhattan, "C:\\Users\\Admin\\Desktop\\df_Manhattan.csv", row.names=FALSE)

write.csv(df_Queens, "C:\\Users\\Admin\\Desktop\\df_Queens.csv", row.names=FALSE)

write.csv(df_Staten_Island, "C:\\Users\\Admin\\Desktop\\df_Staten_Island.csv", row.names=FALSE)

```

```{r Bronx}
capture_recapture_the_bronx <- function(year) {
  lots_year_1 <- df_The_Bronx %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_The_Bronx %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_The_Bronx_Num_Rats <- sapply(11:21, capture_recapture_the_bronx)
df_The_Bronx_Num_Rats <- as.data.frame(df_The_Bronx_Num_Rats)

df_The_Bronx_Num_Rats <- df_The_Bronx_Num_Rats %>%
  add_column(Borough = "BRONX",
             .after = "df_The_Bronx_Num_Rats") 
  
df_The_Bronx_Num_Rats <- df_The_Bronx_Num_Rats %>%
  add_column(Year = 11:21,
             .after = "Borough") 

df_The_Bronx_Num_Rats <- rename(df_The_Bronx_Num_Rats, numRats = df_The_Bronx_Num_Rats)
```

```{r Brooklyn}
capture_recapture_brooklyn <- function(year) {
  lots_year_1 <- df_Brooklyn %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Brooklyn %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Brooklyn_Num_Rats <- sapply(11:21, capture_recapture_brooklyn)
df_Brooklyn_Num_Rats <- as.data.frame(df_Brooklyn_Num_Rats)

df_Brooklyn_Num_Rats <- df_Brooklyn_Num_Rats %>%
  add_column(Borough = "BROOKLYN",
             .after = "df_Brooklyn_Num_Rats") 
  
df_Brooklyn_Num_Rats <- df_Brooklyn_Num_Rats %>%
  add_column(Year = 11:21,
             .after = "Borough") 

df_Brooklyn_Num_Rats <- rename(df_Brooklyn_Num_Rats, numRats = df_Brooklyn_Num_Rats)
```

```{r Manhattan}
capture_recapture_manhattan <- function(year) {
  lots_year_1 <- df_Manhattan %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Manhattan %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Manhattan_Num_Rats <- sapply(11:21, capture_recapture_manhattan)
df_Manhattan_Num_Rats <- as.data.frame(df_Manhattan_Num_Rats)

df_Manhattan_Num_Rats <- df_Manhattan_Num_Rats %>%
  add_column(Borough = "MANHATTAN",
             .after = "df_Manhattan_Num_Rats") 
  
df_Manhattan_Num_Rats <- df_Manhattan_Num_Rats %>%
  add_column(Year = 11:21,
             .after = "Borough") 

df_Manhattan_Num_Rats <- rename(df_Manhattan_Num_Rats, numRats = df_Manhattan_Num_Rats)
```

```{r Queens}
capture_recapture_queens <- function(year) {
  lots_year_1 <- df_Queens %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Queens %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Queens_Num_Rats <- sapply(11:21, capture_recapture_queens)
df_Queens_Num_Rats <- as.data.frame(df_Queens_Num_Rats)

df_Queens_Num_Rats <- df_Queens_Num_Rats %>%
  add_column(Borough = "QUEENS",
             .after = "df_Queens_Num_Rats") 
  
df_Queens_Num_Rats <- df_Queens_Num_Rats %>%
  add_column(Year = 11:21,
             .after = "Borough") 

df_Queens_Num_Rats <- rename(df_Queens_Num_Rats, numRats = df_Queens_Num_Rats)
```

```{r Staten Island}
capture_recapture_staten_island <- function(year) {
  lots_year_1 <- df_Staten_Island %>% filter(Year == year - 1) %>% pull(BBL)
  lots_year_2 <- df_Staten_Island %>% filter(Year == year) %>% pull(BBL)
  number_in_year_1 <- length(lots_year_1)
  number_in_year_2 <- length(lots_year_2)
  number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
  50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
}

df_Staten_Island_Num_Rats <- sapply(11:21, capture_recapture_staten_island)
df_Staten_Island_Num_Rats <- as.data.frame(df_Staten_Island_Num_Rats)

df_Staten_Island_Num_Rats <- df_Staten_Island_Num_Rats %>%
  add_column(Borough = "STATEN ISLAND",
             .after = "df_Staten_Island_Num_Rats") 
  
df_Staten_Island_Num_Rats <- df_Staten_Island_Num_Rats %>%
  add_column(Year = 11:21,
             .after = "Borough") 

df_Staten_Island_Num_Rats <- rename(df_Staten_Island_Num_Rats, numRats = df_Staten_Island_Num_Rats)
```

```{r NYC}
# capture_recapture_nyc <- function(year) {
#   lots_year_1 <- df_NYC %>% filter(Year == year - 1) %>% pull(BBL)
#   lots_year_2 <- df_NYC %>% filter(Year == year) %>% pull(BBL)
#   number_in_year_1 <- length(lots_year_1)
#   number_in_year_2 <- length(lots_year_2)
#   number_in_year_1_and_2 <- sum(lots_year_1 %in% lots_year_2)
#   50 * number_in_year_1 * number_in_year_2 / number_in_year_1_and_2
# }
# 
# df_NYC_Num_Rats <- sapply(11:21, capture_recapture_nyc)
# df_NYC_Num_Rats <- as.data.frame(df_NYC_Num_Rats)
# 
# df_NYC_Num_Rats <- df_NYC_Num_Rats %>%
#   add_column(Group = "NYC",
#              .after = "df_NYC_Num_Rats") 
#   
# df_NYC_Num_Rats <- df_NYC_Num_Rats %>%
#   add_column(Year = 11:21,
#              .after = "Group") 
# 
# df_NYC_Num_Rats <- rename(df_NYC_Num_Rats, numRats = df_NYC_Num_Rats)
```

```{r Cumulative}

df_NYC_Num_Rats <- list( df_Brooklyn_Num_Rats, df_Queens_Num_Rats,  df_Manhattan_Num_Rats, df_The_Bronx_Num_Rats, df_Staten_Island_Num_Rats)

df_NYC_Num_Rats <- Reduce(function(x,y) merge(x,y, all = TRUE), df_NYC_Num_Rats)

df_NYC_Num_Rats <- df_NYC_Num_Rats[order(df_NYC_Num_Rats$numRats),]

graph1 <- ggplot(df_NYC_Num_Rats, aes(x = Year, y = numRats, color = Borough)) +
  geom_line(size = 1.5) + 
  scale_x_continuous(breaks = seq(11,21, by = 1)) + 
  scale_y_continuous(breaks = seq(0,1500000, by = 200000)) +
  labs (title = "Rat Population In Each Borough Over Time", subtitle = "Do rats proliferate faster in certain Boroughs?", x = "Year", y = "Population" ) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) +
  ggsave("graph1.pdf", height = 480, width = 852, units = "pixel")

graph2.anim <- ggplot(df_NYC_Num_Rats, aes(x = Year, y = numRats, fill = Borough)) + 
  geom_area(alpha=0.725) + 
  scale_x_continuous(breaks = seq(11,21, by = 1)) + 
  scale_y_continuous(breaks = seq(0, 4000000, by = 500000)) + 
  labs (title = "Rat Population In NYC", subtitle = "Year: {frame_along}", x = "Year", y = "Population" ) +
  theme_fivethirtyeight() +
  theme(axis.title.y = element_text(), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  transition_reveal(Year) +
  view_follow()

animate(graph2.anim, height = 480, width = 852, fps = 30, duration = 15, end_pause = 90, res = 100)
anim_save("graph2anim.gif")
 
```




